# name: Checkout Current Branch

# on:
#   push:
#     branches:
#       - '**'  # Trigger on push to any branch
#   pull_request:
#     branches:
#       - main  # Trigger on PRs targeting the main branch

# jobs:
#   checkout:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout current branch
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.ref }}  # Checkout the branch that triggered the workflow (push or PR)

#       # - name: Fail delibariately
#       #   run:
#       #     exit 1
#       - name: Show current branch name
#         run: 
#           echo ${{ github.ref }}

#   # second_job:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - name: Show current branch name
#   #       run: 
#   # #         echo ${{ github.ref }}    
#   # third_job:
#   #   runs-on: ubuntu-latest
#   #   needs: [checkout, second_job]
#   #   # if: ${{ failure('checkout') && success('second_job') }}
#   #   if: success()
#   #   steps:
#   #     - name: Show current branch name
#   #       run: 
#   #         echo ${{ github.ref }}    
  
name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
