name: Checkout Current Branch

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  # Checkout the branch that triggered the workflow (push or PR)

      # - name: Fail delibariately
      #   run:
      #     exit 1
      - name: Show current branch name
        run: 
          echo ${{ github.ref }}

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show current branch name
        run: 
          exit 1 # echo ${{ github.ref }}    
  third_job:
    runs-on: ubuntu-latest
    needs: [checkout, second_job]
    # if: ${{ failure('checkout') && success('second_job') }}
    if: failure()
    steps:
      - name: Show current branch name
        run: 
          echo ${{ github.ref }}    
  
